# Generated by Django 4.0 on 2023-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=40)),
                ('released', models.CharField(blank=True, max_length=40)),
                ('mail', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
