# Generated by Django 4.0 on 2023-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_company_alter_application_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='released',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
    ]
