# Generated by Django 4.0 on 2023-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
